global using NUnit.Framework;
global using FluentAssertions;
global using System.Net.Http.Json;
global using Bogus;
global using Dapper;
global using FluentAssertions.Execution;
global using infrastructure.Models;
global using Newtonsoft.Json;
global using Npgsql;