name: Run Playwright tests

on:
  pull_request:
    branches: 
    - main
    - development
  push:
    branches: 
      - main
      - development
  
  
  workflow_dispatch:
 

jobs:
  runPlaywrightTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: |
          cd PlaywrightTests/
          dotnet build
          pwsh bin/Debug/8.0/playwright.ps1 install
          ng build
          dotnet run & sleep 20 && dotnet test && kill -9 $(lsof -t -i:5000)
        
