name: Run Playwright tests

on:
  pull_request:
    branches: 
    - main
    - development
  push:
    branches: 
      - main
      - development
  
  
  workflow_dispatch:
 
 
env:
  DOTNET_VERSION: 8.0

jobs:
  runPlaywrightTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "$DOTNET_VERSION.x"
      - run: |
          cd PlaywrightTests/
          dotnet build
          pwsh bin/Debug/$DOTNET_VERSION/playwright.ps1 install
          ng build
          dotnet run & sleep 20 && dotnet test && kill -9 $(lsof -t -i:5000)
        
